### PR TITLE
Adding contribution guide

### PR DESCRIPTION
**Pull request by AmitRoushan**
Signed-off-by: Amit Roushan <amitroushan.cusat11@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

/kind documentation

**What this PR does / why we need it**:
The PR add contribution guide for community contributions.  
**Which issue(s) this PR fixes**:

Fixes #

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED
kind NOT-TESTED
**Test Report**:

NA
**Special notes for your reviewer**:

### CODE REVIEW

**Review by sushanthakumar — APPROVED** [review]

**Review by skdwriting — COMMENTED** [review]
1. Why dont we make it a common document under https://github.com/sodafoundation/community or https://github.com/sodafoundation/soda
2. Then we can add this specific contribution guide information at https://github.com/orgs/sodafoundation/discussions/24
3. If we want project level also, just create a small doc and just provide the link to common contribution guide

**Review by joseph-v — DISMISSED** [review]
LGTM

**Comment by AmitRoushan** [comment]
@skdwriting added [contribution guide ](https://github.com/sodafoundation/community/blob/main/contribution/contribution-guide.md) in soda community repo
Same has been added as reference here

**Review by sushanthakumar — APPROVED** [review]
LGTM

**Review by joseph-v — APPROVED** [review]

**Pull request merged**
