### PR TITLE
Readme file update

### PR DESCRIPTION
**Pull request by sushanthakumar**
Signed-off-by: sushanthakumar <sushanthakumar@huawei.com>

**What type of PR is this?**
kind documentation

**What this PR does / why we need it**:
This PR updates Readme file with information such as deployent and user guide details, contribution guide, design doc detais

**Which issue(s) this PR fixes**:

Fixes #

**Test Report Added?**:
kind TESTED

**Test Report**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by skdwriting — CHANGES_REQUESTED** [review]
Please add http://bit.ly/soda-starter link for new contributor general information.

**Comment by sushanthakumar** [comment]
> Please add http://bit.ly/soda-starter link for new contributor general information.

Updated

**Review by AmitRoushan — DISMISSED** [review]
LGTM

**Review by AmitRoushan — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
