### PR TITLE
Deploy csi snapshot related CRDs

### PR DESCRIPTION
**Pull request by sushanthakumar**
Signed-off-by: sushanthakumar <sushanthakumar@huawei.com>

**What type of PR is this?**
kind bug fix

**What this PR does / why we need it**:
This PR adds the csi snapshot related CRDs as the deploy dependency during kahu deployment

**Which issue(s) this PR fixes**:

Fixes https://github.com/soda-cdm/kahu/issues/142

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED

**Test Report**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by AmitRoushan — CHANGES_REQUESTED** [review]
IMO, v1beta1 snapshot CRDs can also be attached here

**Comment by SrinivasChilveri** [comment]
LGTM

**Review by joseph-v — APPROVED** [review]
LGTM

**Review by AmitRoushan — APPROVED** [review]
LGTM

**Pull request merged**
