### PR TITLE
Kahu: Creating Backup and Restore Project directory

### PR DESCRIPTION
**Pull request by PravinRanjan10**
Below is the Initial list of project directories.

cmd
 - main.go

controllers

provider
 - lib
   - go

examples

config

docs
- design

test/e2e

### CODE REVIEW

**Comment by PravinRanjan10** [comment]
@skdwriting @wisererik Please review. Thank you

**Comment by sushanthakumar** [comment]
Udpate the name of the folder "doc" to "docs"

**Comment by AmitRoushan** [comment]
@PravinRanjan10 IMO, cxx directory might not be required

**Comment by sushanthakumar** [comment]
@skdwriting @wisererik @doubletao318 pls help to review this PR

**Comment by sushanthakumar** [comment]
LGTM

**Review by sushanthakumar — APPROVED** [review]

**Pull request merged**
